---
- name: Software Install
  yum: 
    name: "{{ item }}"
    state: present
  with_items: "{{ install_name }}"

- name: check default ruby version
  shell: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
