---
- name: Yum update packages
  yum:
    name: "*"
    state: latest

- name: EPEL Repository Install
  yum:
    name: epel-release
    state: present   

- name: K8S Repository Install
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kube*
